// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxodnxejdlxyxeaczpma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14b2RueGVqZGx4eXhlYWN6cG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0ODE2MTgsImV4cCI6MjA3ODA1NzYxOH0.bQ5CgsfUBWU6JXV2cBZIWVB4mRLVVNzZyPvVYpKXaWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});